#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ] ; then
    apt-mark manual bash-config \
 job-scheduler \
 deb-installer \
 disk-manager \
 mx-boot-options \
 mx-bootrepair \
 cleanup-notifier-mx \
 mx-conky \
 mx-datetime \
 mx-locale \
 mx-network-assistant \
 mx-packageinstaller \
 mx-remaster \
 mx-remastercc \
 mx-repo-manager \
 mx-samba-config \
 mx-select-sound \
 mx-service-manager \
 mx-snapshot \
 mx-system-sounds \
 mx-tools \
 mx-tweak \
 mx-usb-unmounter \
 mx-user \
 mx-welcome \
 live-kernel-updater \
 mx-live-usb-maker \
 live-usb-maker \
 quick-system-info-gui \
 conky-toggle-mx \
 ddm-mx \
 formatusb \
 papirus-folder-colors \
 system-keyboard-qt \
 mx-cleanup 
fi

#DEBHELPER#
